"""
Django settings for boreas_mediacion project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-r)vz2%8h*%9wiu4hxq1ra@(++w@%^2)bt8)vvb!kooi8w1&(t$')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')


import sys
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'django_filters',
    'boreas_mediacion',
    'boreas_bot',
]

# Database routers
DATABASE_ROUTERS = [
    'boreas_bot.routers.BoreasBotRouter',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'boreas_mediacion.metrics.PrometheusMiddleware',
]

ROOT_URLCONF = 'boreas_mediacion.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        }
    }
]

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases


# Usar DATABASE_URL si está disponible (para Docker/producción)
if os.getenv('DATABASE_URL'):
    import dj_database_url
    DATABASES = {
        'default': dj_database_url.config(
            default=os.getenv('DATABASE_URL'),
            conn_max_age=600
        ),
        'external': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('EXTERNAL_DB_NAME', 'boreas'),
            'USER': os.getenv('EXTERNAL_DB_USER', 'boreas_ro') or 'boreas_ro',
            'PASSWORD': os.getenv('EXTERNAL_DB_PASSWORD', ''),
            'HOST': os.getenv('EXTERNAL_DB_HOST', 'mqtt.rg-iotsolutions.com'),
            'PORT': os.getenv('EXTERNAL_DB_PORT', '5433'),
            'OPTIONS': {
                'options': f'-c search_path={os.getenv("EXTERNAL_DB_SCHEMA", "public")}'
            }
        }
    }
else:
    # Fallback a PostgreSQL local o SQLite
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('DB_NAME'),
            'USER': os.getenv('DB_USER'),
            'PASSWORD': os.getenv('DB_PASSWORD'),
            'HOST': os.getenv('DB_HOST'),
            'PORT': os.getenv('DB_PORT'),
        },
        'external': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('EXTERNAL_DB_NAME', 'boreas'),
            'USER': os.getenv('EXTERNAL_DB_USER', 'boreas_ro') or 'boreas_ro',
            'PASSWORD': os.getenv('EXTERNAL_DB_PASSWORD', 'BoreasRO2021'),
            'HOST': os.getenv('EXTERNAL_DB_HOST', 'mqtt.rg-iotsolutions.com'),
            'PORT': os.getenv('EXTERNAL_DB_PORT', '5433'),
            'OPTIONS': {
                'options': f'-c search_path={os.getenv("EXTERNAL_DB_SCHEMA", "public")}'
            }
        }
    }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Europe/Paris'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = '/app/staticfiles'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'boreas_mediacion', 'static')]

# Media files (User uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# Redirect to dashboard after login
LOGIN_REDIRECT_URL = '/dashboard/family-messages/'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# MQTT_SERVER = 'broker.emqx.io'
# MQTT_PORT = 1883
# MQTT_KEEPALIVE = 60
# MQTT_USER = 'pablo'
# MQTT_PASSWORD = 'pablo'

MQTT_SERVER = os.getenv('MQTT_SERVER', 'mqtt.rg-iotsolutions.com')
MQTT_PORT = int(os.getenv('MQTT_PORT', '1883'))
MQTT_KEEPALIVE = int(os.getenv('MQTT_KEEPALIVE', '60'))
MQTT_USER = os.getenv('MQTT_USER', 'pablo')
MQTT_PASSWORD = os.getenv('MQTT_PASSWORD', 'pabloDev1234')
MQTT_TLS = os.getenv('MQTT_TLS', None)


REST_FRAMEWORK = {
    # Use Django's standard `django.contrib.auth` permissions,
    # or allow read-only access for unauthenticated users.
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly'
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10
}

# Email Configuration - Port 587 with TLS (as per mail server specs)
EMAIL_BACKEND = 'boreas_mediacion.email_backend.FixedHELOSMTPBackend'
EMAIL_HOST = os.getenv('EMAIL_HOST', 'mail.rggestionyenergia.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', 'alonsogpablo@rggestionyenergia.com')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'alonsogpablo@rggestionyenergia.com')
SERVER_EMAIL = 'boreas@rggestionyenergia.com'

# Import logging configuration
try:
    from ..logging_config import LOGGING
except ImportError:
    LOGGING = None
