# Generated by Django 4.2.27 on 2026-01-29 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AemetStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('province', models.CharField(blank=True, max_length=100, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DatadisCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', help_text='NIF/CIF del usuario', max_length=100, unique=True)),
                ('password', models.CharField(default='', help_text='Contraseña de acceso', max_length=200)),
                ('auth_token', models.TextField(blank=True, default='', help_text='Token Bearer de autenticación', null=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('last_auth', models.DateTimeField(blank=True, help_text='Última autenticación exitosa', null=True)),
                ('last_sync', models.DateTimeField(blank=True, help_text='Última sincronización de datos', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'DATADIS Credentials',
                'verbose_name_plural': 'DATADIS Credentials',
            },
        ),
        migrations.CreateModel(
            name='MQTT_broker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='unknown', max_length=100)),
                ('server', models.CharField(default='localhost', max_length=100)),
                ('port', models.IntegerField(default=1883)),
                ('keepalive', models.IntegerField(default=60)),
                ('description', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('active', models.BooleanField(default=True)),
                ('user', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('password', models.CharField(blank=True, default='', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MQTT_device_family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='unknown', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MQTT_tx',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(default='unknown', max_length=100)),
                ('payload', models.CharField(blank=True, default='', max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='router_parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.CharField(default='unknown', max_length=100)),
                ('description', models.CharField(blank=True, default='', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='sensor_actuacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(default='unknown', max_length=100)),
                ('command', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('parameter', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SigfoxDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(db_index=True, default='', max_length=50, unique=True)),
                ('firmware', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('last_payload', models.JSONField(blank=True, default=dict)),
                ('last_co2', models.IntegerField(blank=True, null=True)),
                ('last_temp', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('last_hum', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('last_base', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sigfox Device',
                'verbose_name_plural': 'Sigfox Devices',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_type', models.CharField(choices=[('email', 'Email Configuration'), ('alert', 'Alert Configuration'), ('airflow', 'Airflow Configuration'), ('general', 'General Configuration')], default='general', max_length=50)),
                ('key', models.CharField(db_index=True, default='', help_text='Clave de configuración (ej: airflow_alert_email)', max_length=100, unique=True)),
                ('value', models.TextField(default='', help_text='Valor de la configuración')),
                ('description', models.TextField(blank=True, default='', help_text='Descripción de la configuración', null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Configuration',
                'verbose_name_plural': 'System Configurations',
                'ordering': ['config_type', 'key'],
            },
        ),
        migrations.CreateModel(
            name='TopicMessageTimeout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(db_index=True, help_text='Tópico MQTT a monitorear', max_length=255, unique=True)),
                ('timeout_minutes', models.IntegerField(default=60, help_text='Minutos sin mensajes antes de alerta')),
                ('active', models.BooleanField(default=True)),
                ('last_message_time', models.DateTimeField(blank=True, help_text='Hora del último mensaje recibido', null=True)),
                ('alert_sent', models.BooleanField(default=False, help_text='Si ya se envió alerta por timeout')),
                ('alert_sent_at', models.DateTimeField(blank=True, help_text='Cuándo se envió la última alerta', null=True)),
                ('notification_recipients', models.TextField(default='', help_text='Destinatarios separados por comas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Topic Message Timeout',
                'verbose_name_plural': 'Topic Message Timeouts',
                'ordering': ['topic'],
            },
        ),
        migrations.CreateModel(
            name='WirelessLogic_SIM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iccid', models.CharField(db_index=True, default='', help_text='Integrated Circuit Card Identifier', max_length=20, unique=True)),
                ('msisdn', models.CharField(blank=True, default='', help_text='Mobile Station International Subscriber Directory Number', max_length=20, null=True)),
                ('imsi', models.CharField(blank=True, default='', help_text='International Mobile Subscriber Identity', max_length=20, null=True)),
                ('status', models.CharField(blank=True, default='', help_text='Estado actual de la SIM', max_length=50, null=True)),
                ('activation_date', models.DateTimeField(blank=True, help_text='Fecha de activación', null=True)),
                ('tariff_name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('account_name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('network', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('roaming_network', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('raw_data', models.JSONField(default=dict, help_text='Datos completos de la API')),
                ('last_sync', models.DateTimeField(auto_now=True, help_text='Última sincronización con la API')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'WirelessLogic SIM',
                'verbose_name_plural': 'WirelessLogic SIMs',
                'ordering': ['-last_sync'],
            },
        ),
        migrations.CreateModel(
            name='SigfoxReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('firmware', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('co2', models.IntegerField(blank=True, null=True)),
                ('temp', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('hum', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('base', models.IntegerField(blank=True, null=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='boreas_mediacion.sigfoxdevice')),
            ],
            options={
                'verbose_name': 'Sigfox Reading',
                'verbose_name_plural': 'Sigfox Readings',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='sensor_command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(default='unknown', max_length=100)),
                ('circuit', models.IntegerField(default=0)),
                ('actuacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boreas_mediacion.sensor_actuacion')),
            ],
        ),
        migrations.CreateModel(
            name='router_get',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boreas_mediacion.router_parameter')),
            ],
        ),
        migrations.CreateModel(
            name='MQTT_topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(default='unknown', max_length=100)),
                ('qos', models.IntegerField(default=0)),
                ('description', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('active', models.BooleanField(default=False)),
                ('ro_rw', models.CharField(default='ro', max_length=2)),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boreas_mediacion.mqtt_broker')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boreas_mediacion.mqtt_device_family')),
            ],
        ),
        migrations.CreateModel(
            name='MQTT_feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='unknown', max_length=100)),
                ('description', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boreas_mediacion.mqtt_topic')),
            ],
        ),
        migrations.CreateModel(
            name='DatadisSupply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cups', models.CharField(db_index=True, default='', help_text='Código Universal de Punto de Suministro', max_length=22, unique=True)),
                ('address', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('postal_code', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('province', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('municipality', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('distributor', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('distributor_code', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('point_type', models.IntegerField(blank=True, help_text='Tipo de punto: 1-5', null=True)),
                ('valid_date_from', models.DateField(blank=True, null=True)),
                ('valid_date_to', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('raw_data', models.JSONField(default=dict, help_text='Datos completos de la API')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credentials', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplies', to='boreas_mediacion.datadiscredentials')),
            ],
            options={
                'verbose_name': 'DATADIS Supply Point',
                'verbose_name_plural': 'DATADIS Supply Points',
                'ordering': ['cups'],
            },
        ),
        migrations.CreateModel(
            name='WirelessLogic_Usage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateTimeField(help_text='Inicio del período')),
                ('period_end', models.DateTimeField(help_text='Fin del período')),
                ('data_used_mb', models.DecimalField(decimal_places=2, default=0, help_text='Datos usados en MB', max_digits=12)),
                ('sms_sent', models.IntegerField(default=0)),
                ('sms_received', models.IntegerField(default=0)),
                ('voice_minutes', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('raw_data', models.JSONField(default=dict, help_text='Datos completos de uso')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='boreas_mediacion.wirelesslogic_sim')),
            ],
            options={
                'verbose_name': 'WirelessLogic Usage',
                'verbose_name_plural': 'WirelessLogic Usages',
                'ordering': ['-period_end'],
                'unique_together': {('sim', 'period_start', 'period_end')},
            },
        ),
        migrations.CreateModel(
            name='reported_measure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_time', models.DateTimeField(auto_now=True)),
                ('device', models.JSONField(default=dict)),
                ('device_id', models.CharField(default='unknown', max_length=100)),
                ('measures', models.JSONField(default=dict)),
                ('feed', models.CharField(default='unknown', max_length=100)),
                ('device_family_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='boreas_mediacion.mqtt_device_family')),
            ],
            options={
                'unique_together': {('feed', 'device_id')},
            },
        ),
        migrations.CreateModel(
            name='AemetData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='boreas_mediacion.aemetstation')),
            ],
            options={
                'ordering': ['-timestamp'],
                'unique_together': {('station', 'timestamp')},
            },
        ),
    ]
