# Generated by Django 4.2 on 2023-05-15 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mqtt_msg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_time', models.DateTimeField(auto_now=True)),
                ('device', models.JSONField(unique=True)),
                ('measures', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='reported_measure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_time', models.DateTimeField(auto_now=True)),
                ('device', models.JSONField()),
                ('measures', models.JSONField()),
            ],
        ),
    ]
