# Generated by Django 4.2 on 2023-05-16 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boreas_mediacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mqtt_msg',
            name='device_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
