# Generated by Django 4.2.28 on 2026-02-06 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boreas_mediacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectedAnomaly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('device_id', models.CharField(db_index=True, max_length=100)),
                ('client', models.CharField(blank=True, max_length=255, null=True)),
                ('metric_name', models.CharField(db_index=True, max_length=100)),
                ('metric_value', models.FloatField()),
                ('anomaly_type', models.CharField(help_text='Tipo: statistical_outlier, sudden_change, etc.', max_length=50)),
                ('severity', models.FloatField(help_text='Severidad (ej: z-score)')),
                ('baseline_mean', models.FloatField(help_text='Media histórica del métrico')),
                ('baseline_std', models.FloatField(help_text='Desviación estándar histórica')),
                ('detected_at', models.DateTimeField(db_index=True, help_text='Momento de detección')),
                ('details', models.JSONField(default=dict, help_text='Detalles adicionales (z_score, baseline_min, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Detected Anomaly',
                'verbose_name_plural': 'Detected Anomalies',
                'db_table': 'boreas_mediacion_detected_anomaly',
                'ordering': ['-detected_at'],
                'indexes': [models.Index(fields=['device_id', 'metric_name', '-detected_at'], name='boreas_medi_device__cae2ce_idx'), models.Index(fields=['anomaly_type', '-detected_at'], name='boreas_medi_anomaly_0cd32a_idx')],
            },
        ),
    ]
