# Generated by Django 4.2 on 2026-01-20 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boreas_mediacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='datadismaxpower',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='datadismaxpower',
            name='supply',
        ),
        migrations.DeleteModel(
            name='DatadisConsumption',
        ),
        migrations.DeleteModel(
            name='DatadisMaxPower',
        ),
    ]
