# Generated by Django 4.2 on 2023-05-01 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boreas_mediacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mqtt_msg',
            name='report_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
