# Generated by Django 4.2.27 on 2026-01-29 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boreas_mediacion', '0002_aemetstation_aemetdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mqtt_msg',
            name='device_family',
        ),
        migrations.RemoveField(
            model_name='router_get',
            name='device_id',
        ),
        migrations.AddField(
            model_name='reported_measure',
            name='device_family_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='boreas_mediacion.mqtt_device_family'),
        ),
        migrations.AlterField(
            model_name='sensor_command',
            name='device_id',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.DeleteModel(
            name='Alert',
        ),
        migrations.DeleteModel(
            name='AlertRule',
        ),
        migrations.DeleteModel(
            name='mqtt_msg',
        ),
    ]
