# Generated by Django 4.2.28 on 2026-02-11 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boreas_mediacion', '0002_drop_devicetype_mapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='gadget',
            name='uuid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='gadget',
            name='uuid_ip',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
