# Generated by Django 4.2 on 2026-01-21 11:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('boreas_mediacion', '0002_alter_datadismaxpower_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertrule',
            name='rule_type',
            field=models.CharField(choices=[('disk_space', 'Disk Space'), ('device_connection', 'Device Connection'), ('aemet_data', 'AEMET Weather Data'), ('topic_message_timeout', 'Topic Message Timeout'), ('families_last_readings', 'Families Last Readings Summary'), ('custom', 'Custom Check')], db_index=True, default='custom', max_length=50),
        ),
        migrations.AlterField(
            model_name='mqtt_msg',
            name='report_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
