# Generated by Django 4.2.27 on 2026-02-04 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boreas_mediacion', '0002_mqtt_topic_monitored'),
    ]

    operations = [
        migrations.AddField(
            model_name='reported_measure',
            name='nanoenvi_client',
            field=models.CharField(blank=True, help_text='Client from devicesNANOENVI', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reported_measure',
            name='nanoenvi_name',
            field=models.CharField(blank=True, help_text='Device name from devicesNANOENVI', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reported_measure',
            name='nanoenvi_uuid',
            field=models.CharField(blank=True, help_text='UUID from devicesNANOENVI table', max_length=255, null=True),
        ),
    ]
