# Generated by Django 4.2.27 on 2026-02-04 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boreas_mediacion', '0002_reported_measure_timeseries'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='reported_measure',
            new_name='boreas_medi_device__8bba22_idx',
            old_name='reported_measure_device_feed_time_idx',
        ),
    ]
