# Generated by Django 4.2 on 2023-05-02 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boreas_mediacion', '0002_mqtt_msg_report_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mqtt_msg',
            old_name='measure',
            new_name='measures',
        ),
    ]
