# Generated by Django 4.2 on 2026-01-01 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boreas_mediacion', '0002_mqtt_msg_device_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='MQTT_broker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('server', models.CharField(max_length=100)),
                ('port', models.IntegerField(default=1883)),
                ('keepalive', models.IntegerField(default=60)),
                ('description', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=False)),
                ('user', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MQTT_device_family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MQTT_tx',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100)),
                ('payload', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='router_parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='sensor_actuacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('command', models.CharField(max_length=100)),
                ('parameter', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='mqtt_msg',
            options={'ordering': ['device_id']},
        ),
        migrations.AddField(
            model_name='mqtt_msg',
            name='feed',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='reported_measure',
            name='device_id',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='reported_measure',
            name='feed',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='mqtt_msg',
            name='device',
            field=models.JSONField(default=dict, unique=True),
        ),
        migrations.AlterField(
            model_name='mqtt_msg',
            name='device_id',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='mqtt_msg',
            name='measures',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='reported_measure',
            name='device',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='reported_measure',
            name='measures',
            field=models.JSONField(default=dict),
        ),
        migrations.CreateModel(
            name='sensor_command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('circuit', models.IntegerField(default=0)),
                ('actuacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boreas_mediacion.sensor_actuacion')),
                ('device_id', models.ForeignKey(limit_choices_to={'device_id__icontains': '-', 'feed__iexact': 'shellies'}, on_delete=django.db.models.deletion.CASCADE, to='boreas_mediacion.mqtt_msg')),
            ],
        ),
        migrations.CreateModel(
            name='router_get',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.ForeignKey(limit_choices_to={'feed__iexact': 'router'}, on_delete=django.db.models.deletion.CASCADE, to='boreas_mediacion.mqtt_msg')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boreas_mediacion.router_parameter')),
            ],
        ),
        migrations.CreateModel(
            name='MQTT_topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100)),
                ('qos', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=False)),
                ('ro_rw', models.CharField(default='ro', max_length=2)),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boreas_mediacion.mqtt_broker')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boreas_mediacion.mqtt_device_family')),
            ],
        ),
        migrations.CreateModel(
            name='MQTT_feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boreas_mediacion.mqtt_topic')),
            ],
        ),
        migrations.AddField(
            model_name='mqtt_msg',
            name='device_family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='boreas_mediacion.mqtt_device_family'),
        ),
    ]
