# Generated by Django 4.2.27 on 2026-02-08 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boreas_mediacion', '0003_convert_reported_measure_to_hypertable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reported_measure',
            options={'managed': False},
        ),
    ]
