# Generated by Django 4.2 on 2026-01-05 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boreas_mediacion', '0003_mqtt_broker_mqtt_device_family_mqtt_tx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WirelessLogic_SIM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iccid', models.CharField(db_index=True, help_text='Integrated Circuit Card Identifier', max_length=20, unique=True)),
                ('msisdn', models.CharField(blank=True, help_text='Mobile Station International Subscriber Directory Number', max_length=20, null=True)),
                ('imsi', models.CharField(blank=True, help_text='International Mobile Subscriber Identity', max_length=20, null=True)),
                ('status', models.CharField(blank=True, help_text='Estado actual de la SIM', max_length=50, null=True)),
                ('activation_date', models.DateTimeField(blank=True, help_text='Fecha de activación', null=True)),
                ('tariff_name', models.CharField(blank=True, max_length=200, null=True)),
                ('account_name', models.CharField(blank=True, max_length=200, null=True)),
                ('network', models.CharField(blank=True, max_length=100, null=True)),
                ('roaming_network', models.CharField(blank=True, max_length=100, null=True)),
                ('raw_data', models.JSONField(default=dict, help_text='Datos completos de la API')),
                ('last_sync', models.DateTimeField(auto_now=True, help_text='Última sincronización con la API')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'WirelessLogic SIM',
                'verbose_name_plural': 'WirelessLogic SIMs',
                'ordering': ['-last_sync'],
            },
        ),
        migrations.CreateModel(
            name='WirelessLogic_Usage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateTimeField(help_text='Inicio del período')),
                ('period_end', models.DateTimeField(help_text='Fin del período')),
                ('data_used_mb', models.DecimalField(decimal_places=2, default=0, help_text='Datos usados en MB', max_digits=12)),
                ('sms_sent', models.IntegerField(default=0)),
                ('sms_received', models.IntegerField(default=0)),
                ('voice_minutes', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('raw_data', models.JSONField(default=dict, help_text='Datos completos de uso')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='boreas_mediacion.wirelesslogic_sim')),
            ],
            options={
                'verbose_name': 'WirelessLogic Usage',
                'verbose_name_plural': 'WirelessLogic Usages',
                'ordering': ['-period_end'],
                'unique_together': {('sim', 'period_start', 'period_end')},
            },
        ),
    ]
