# Generated by Django 4.2 on 2023-05-11 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boreas_mediacion', '0003_rename_measure_mqtt_msg_measures'),
    ]

    operations = [
        migrations.CreateModel(
            name='reported_measure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_time', models.DateTimeField(auto_now=True)),
                ('device', models.JSONField()),
                ('measures', models.JSONField()),
            ],
        ),
    ]
