# Generated by Django 4.2.28 on 2026-02-18 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boreas_mediacion', '0003_gadget_uuid_gadget_uuid_ip'),
    ]

    operations = [
        migrations.CreateModel(
            name='APITaskTrigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'API Task Trigger',
                'verbose_name_plural': 'API Task Triggers',
            },
        ),
    ]
