# Generated by Django 4.2.27 on 2026-02-04 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boreas_mediacion', '0003_reported_measure_nanoenvi_client_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceMonitoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=255)),
                ('source', models.CharField(choices=[('nanoenvi', 'NanoENVI'), ('co2', 'CO2'), ('routers', 'Routers'), ('shellies', 'Shellies')], max_length=50)),
                ('monitored', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('uuid', 'source')},
            },
        ),
    ]
