# Generated by Django 4.2.27 on 2026-02-04 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boreas_mediacion', '0004_devicemonitoring'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mqtt_topic',
            name='monitored',
        ),
    ]
