# Generated by Django 4.2 on 2026-01-05 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boreas_mediacion', '0004_wirelesslogic_sim_wirelesslogic_usage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SigfoxDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('firmware', models.CharField(blank=True, max_length=10, null=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('last_payload', models.JSONField(blank=True, default=dict)),
                ('last_co2', models.IntegerField(blank=True, null=True)),
                ('last_temp', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('last_hum', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('last_base', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sigfox Device',
                'verbose_name_plural': 'Sigfox Devices',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SigfoxReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('firmware', models.CharField(blank=True, max_length=10, null=True)),
                ('co2', models.IntegerField(blank=True, null=True)),
                ('temp', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('hum', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('base', models.IntegerField(blank=True, null=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='boreas_mediacion.sigfoxdevice')),
            ],
            options={
                'verbose_name': 'Sigfox Reading',
                'verbose_name_plural': 'Sigfox Readings',
                'ordering': ['-timestamp'],
            },
        ),
    ]
