# Generated by Django 4.2 on 2023-05-14 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boreas_mediacion', '0004_reported_measure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mqtt_msg',
            name='device',
            field=models.JSONField(unique=True),
        ),
    ]
