# Generated by Django 4.2.27 on 2026-02-08 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boreas_mediacion', '0005_add_retention_policy'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='reported_measure',
            table='boreas_mediacion_reported_measure',
        ),
    ]
