# Generated by Django 4.2 on 2026-01-08 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boreas_mediacion', '0005_add_sigfox_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatadisCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='NIF/CIF del usuario', max_length=100, unique=True)),
                ('password', models.CharField(help_text='Contraseña de acceso', max_length=200)),
                ('auth_token', models.TextField(blank=True, help_text='Token Bearer de autenticación', null=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('last_auth', models.DateTimeField(blank=True, help_text='Última autenticación exitosa', null=True)),
                ('last_sync', models.DateTimeField(blank=True, help_text='Última sincronización de datos', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'DATADIS Credentials',
                'verbose_name_plural': 'DATADIS Credentials',
            },
        ),
        migrations.CreateModel(
            name='DatadisSupply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cups', models.CharField(db_index=True, help_text='Código Universal de Punto de Suministro', max_length=22, unique=True)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True)),
                ('province', models.CharField(blank=True, max_length=100, null=True)),
                ('municipality', models.CharField(blank=True, max_length=200, null=True)),
                ('distributor', models.CharField(blank=True, max_length=100, null=True)),
                ('distributor_code', models.CharField(blank=True, max_length=10, null=True)),
                ('point_type', models.IntegerField(blank=True, help_text='Tipo de punto: 1-5', null=True)),
                ('valid_date_from', models.DateField(blank=True, null=True)),
                ('valid_date_to', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('raw_data', models.JSONField(default=dict, help_text='Datos completos de la API')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credentials', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplies', to='boreas_mediacion.datadiscredentials')),
            ],
            options={
                'verbose_name': 'DATADIS Supply Point',
                'verbose_name_plural': 'DATADIS Supply Points',
                'ordering': ['cups'],
            },
        ),
        migrations.CreateModel(
            name='DatadisMaxPower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('time', models.CharField(blank=True, max_length=10, null=True)),
                ('max_power_kw', models.DecimalField(blank=True, decimal_places=3, help_text='Potencia máxima en kW', max_digits=12, null=True)),
                ('raw_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='max_power_records', to='boreas_mediacion.datadissupply')),
            ],
            options={
                'verbose_name': 'DATADIS Max Power',
                'verbose_name_plural': 'DATADIS Max Powers',
                'ordering': ['-date', '-time'],
                'unique_together': {('supply', 'date', 'time')},
            },
        ),
        migrations.CreateModel(
            name='DatadisConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('time', models.CharField(blank=True, help_text='Hora en formato HH:MM', max_length=10, null=True)),
                ('consumption_kwh', models.DecimalField(blank=True, decimal_places=3, help_text='Consumo en kWh', max_digits=12, null=True)),
                ('obtained_method', models.CharField(blank=True, help_text='Método de obtención', max_length=50, null=True)),
                ('measurement_type', models.CharField(default='0', help_text='0: horario, 1: cuartohorario', max_length=10)),
                ('raw_data', models.JSONField(default=dict, help_text='Datos completos del registro')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumption_records', to='boreas_mediacion.datadissupply')),
            ],
            options={
                'verbose_name': 'DATADIS Consumption',
                'verbose_name_plural': 'DATADIS Consumptions',
                'ordering': ['-date', '-time'],
                'unique_together': {('supply', 'date', 'time')},
            },
        ),
    ]
