# Generated by Django 4.2.27 on 2026-02-08 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boreas_mediacion', '0006_alter_reported_measure_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceTypeMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_device_type_name', models.CharField(help_text="External device type name (e.g., 'Router', 'Water Meter')", max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Device Type Mapping',
                'verbose_name_plural': 'Device Type Mappings',
                'db_table': 'boreas_mediacion_device_type_mapping',
                'ordering': ['external_device_type_name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExternalDeviceMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_device_id', models.CharField(db_index=True, help_text='Unique external device identifier', max_length=255, unique=True)),
                ('external_alias', models.CharField(blank=True, help_text='Friendly name for the device', max_length=255, null=True)),
                ('internal_device_uuid', models.CharField(blank=True, help_text='UUID linking to internal system', max_length=255, null=True)),
                ('client_name', models.CharField(blank=True, db_index=True, help_text='Client/Organization name', max_length=255, null=True)),
                ('location_name', models.CharField(blank=True, help_text='Physical location', max_length=255, null=True)),
                ('group_name', models.CharField(blank=True, help_text='Logical grouping', max_length=255, null=True)),
                ('purchase_date', models.DateField(blank=True, help_text='Device acquisition date', null=True)),
                ('sale_date', models.DateField(blank=True, help_text='Device sales/disposal date', null=True)),
                ('status', models.CharField(blank=True, help_text='Status: Venta, Stock, etc.', max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Device is active')),
                ('metadata', models.JSONField(default=dict, help_text='Flexible metadata: device_type, group_name, crawl_date, crawled_from, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'External Device Mapping',
                'verbose_name_plural': 'External Device Mappings',
                'db_table': 'boreas_mediacion_external_device_mapping',
                'ordering': ['-updated_at'],
                'managed': False,
            },
        ),
    ]
