# Generated by Django 4.2.27 on 2026-02-08 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boreas_mediacion', '0007_devicetypemapping_externaldevicemapping'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='devicemonitoring',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='devicemonitoring',
            name='external_device',
            field=models.OneToOneField(blank=True, db_column='external_device_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitoring', to='boreas_mediacion.externaldevicemapping', to_field='external_device_id'),
        ),
        migrations.AlterField(
            model_name='devicemonitoring',
            name='source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='devicemonitoring',
            name='uuid',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
