# Generated by Django 4.2.27 on 2026-02-08 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boreas_mediacion', '0008_alter_devicemonitoring_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicemonitoring',
            name='source',
        ),
    ]
